[package]
name = "in1weekend"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
image = "0.20.1"
log = "0.4"
nalgebra = "0.16"
pretty_env_logger = "0.2.5"
rand = "0.5.5"
